<?php

namespace Tests;

use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    /**
     * Creates a test user and adds it to the database.
     * @return User
     */ 
    protected function CreateTestUser()
    {
        $testUsername = 'user' . str_random(4);
        $testUser = factory(User::class)->create(
            [
                // password, last name, and username are not generated by Laravel factory
                'password' => Hash::make('TestCurrentPassword'),
                'lastname' => 'User',
                'username' => $testUsername
            ]
        );
        return $testUser;
    }
    

}
