<?php

namespace Tests;

use App\User;
use Illuminate\Support\Facades\Hash;
use Illuminate\Foundation\Testing\TestCase as BaseTestCase;
use DB;
use Auth;

abstract class TestCase extends BaseTestCase
{
    use CreatesApplication;

    /**
     * Creates a test user and adds it to the database. The user has password 'TestPassword'.
     * @return User
     */ 
    protected function CreateTestUser()
    {
        $testUsername = 'user' . str_random(4);
        $testUser = factory(User::class)->create(
            [
                // password, last name, and username are not generated by Laravel factory
                'password' => Hash::make('TestPassword'),
                'lastname' => 'User',
                'username' => $testUsername
            ]
        );
        return $testUser;
    }

    /**
     * Creates a test user with administrator status and adds it to the database. The user has password 'TestPassword'.
     * @return User
     */ 
    protected function CreateTestAdmin()
    {
        $testUsername = 'admin' . str_random(4);
        $testUser = factory(User::class)->create(
            [
                // password, last name, and username are not generated by Laravel factory
                'password' => Hash::make('TestPassword'),
                'lastname' => 'User',
                'username' => $testUsername
            ]
        );

        // Make the user an admin
        DB::table('users')->where('id', $testUser->id)->update(['isAdmin' => 1]);
        
        // refresh user after updating admin status
        $testUser->refresh();
        //Auth::user()->refresh();

        return $testUser;
    }

}
